### ISSUE TITLE
Do you have Discord?

### ISSUE THREAD

**Issue by TheGreyRaven** [JReverse/SnapTwink#2]
Hi!

I'm currently working on a similar project to yours and I would love to ask you a couple of things, do you have Discord by any change?

Have a great day!

**Comment by JReverse** [comment]
Hello, Unfortunately my discord is personal to business / close friends. You can ask your questions here and I will try to assist you,

**Comment by TheGreyRaven** [comment]
I fully understand!
I'm currently working on a similar project to yours called SnapTrap which will soon be open-source and here is a short preview of it: https://imgur.com/eQajOox
I was going to ask if perhaps you would like to work on a project togheter, though I saw now in your README that you have halted your project so you might not be interested.

**Comment by JReverse** [comment]
@TheGreyRaven Look really nice. Are all the features currently working? I mean I could help. It's just i bought the iPhone 13 Pro Max although I still will have android to development. What do you need help with?

**Comment by TheGreyRaven** [comment]
For now it has the follwing:

- Screenshot bypass
- Saving snaps and stories (through the path: /data/user/0/com.snapchat.android/files/file_manager/) It does not copy them to a new directory yet but it can find the files.

I would need some help with researching stuff like disabling view timer, ads etc.
It would also be nice to have someone that could help test everything too and make sure it works on other devices and not just mine! 😄
