### ISSUE TITLE
Where can i download snaptwink?

### ISSUE THREAD

**Issue by Lucky056** [JReverse/SnapTwink#3]
I have been following the repo and it seems that the project is finally back but there is no download or release available of snaptwink. I would love to use the project but I can't find any releases yet. Also I tried to reach out to you earlier. Since snapchat now supports substratum which gives dark or black theme to snapchat!

**Comment by JReverse** [comment]
Soon updating the classes

**Comment by JReverse** [comment]
https://github.com/JReverse/SnapTwink/releases/tag/11.57.0.35
